-- ==============================================================================
-- जिला प्रशासन कोण्डागांव (छ०ग०) - नोडल अधिकारी मास्टर एवं अधिकारी सूची (Seed Data)
-- ==============================================================================

-- 1. Insert Masters
INSERT INTO public.masters (id, district, blocks, panchayats) VALUES ('kondagaon_master', 'कोण्डागांव', '["बड़ेराजपुर","केशकाल","फरसगांव","कोंडागांव","माकडी"]'::jsonb, '{"बड़ेराजपुर":["बाँसकोट","तितरवण्ड","बड़बत्तर","ढोढरा","रामपुर","बस्तरबुड्रा","पिटेचुवा","खरगांव","जिरीपारा","बैजनपुरी","खलारी","कोसमी","हात्मा","कोरहोबेड़ा","कोरगांव","टेंवसा","कलगांव","कोंगेरा","सोनपुर","पेण्ड्रावन","होनावण्डी","बाड़ागांव","काँदेकरा","मचली","पारोण्ड","खजरावण्ड","आमगांव","बड़ेराजपुर","छोटेराजपुर","माड़ोकी खरगांव","कोपरा","छिन्दली","धामनपुरी","किबड़ा","बालेंगा","लिहागांव","पलना","चिचाड़ी","सालना","मारंगपुरी","केरागांव","हरवेल","पीढ़ापाल","नौकाबेड़ा","जोड़ेकेरा","गम्हरी","विश्रामपुरी ''अ''","विश्रामपुरी ''ब''","बीरापारा"],"कोण्डागांव":["बनियागांव","दहीकोंगा","जुगानी","बम्हनी","लंजोड़ा"],"केशकाल":["बटराली","अरण्डी","तमोरा","दादरगढ़","सुरदोंग"],"माकड़ी":["अनंतपुर","बालेंग","कांगोली","रांधना","शामपुर"],"फरसगांव":["पासंगी","बड़ाडोंगर","मांझीआठगांव","भोंगापाल","पाटला"],"बड़ेराजपुर":["बाँसकोट","तितरवण्ड","बड़बत्तर","ढोढरा","रामपुर","बस्तरबुड्रा","पिटेचुवा","खरगांव","जिरीपारा","बैजनपुरी","खलारी","कोसमी","हात्मा","कोरहोबेड़ा","कोरगांव","टेंवसा","कलगांव","कोंगेरा","सोनपुर","पेण्ड्रावन","होनावण्डी","बाड़ागांव","काँदेकरा","मचली","पारोण्ड","खजरावण्ड","आमगांव","बड़ेराजपुर","छोटेराजपुर","माड़ोकी खरगांव","कोपरा","छिन्दली","धामनपुरी","किबड़ा","बालेंगा","लिहागांव","पलना","चिचाड़ी","सालना","मारंगपुरी","केरागांव","हरवेल","पीढ़ापाल","नौकाबेड़ा","जोड़ेकेरा","गम्हरी","विश्रामपुरी ''अ''","विश्रामपुरी ''ब''","बीरापारा"],"कोंडागांव":["बनियागांव","दहीकोंगा","जुगानी","बम्हनी","लंजोड़ा"],"माकडी":["अनंतपुर","बालेंग","कांगोली","रांधना","शामपुर"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET blocks = EXCLUDED.blocks, panchayats = EXCLUDED.panchayats;

-- 2. Insert Nodal Officers (69 officers)
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-1', 1, 'श्री लखेश्वर यादव', 'डिप्टी कलेक्टर, जिला कोण्डागांव', '7000680294', 'बड़ेराजपुर', 'कोण्डागांव', 'बाँसकोट', '["बाँसकोट"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-2', 2, 'श्री कृपेन्द्र तिवारी', 'सहायक आयुक्त, आदिवासी विकास', '8085989479', 'बड़ेराजपुर', 'कोण्डागांव', 'तितरवण्ड', '["तितरवण्ड"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-3', 3, 'श्री कैलाश मरकाम', 'उप संचालक कृषि', '7999577532', 'बड़ेराजपुर', 'कोण्डागांव', 'बड़बत्तर', '["बड़बत्तर"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-4', 4, 'श्रीमती अंजना एक्का', 'जिला प्रबन्धक नागरिक आपूर्ति निगम', '9827962668', 'बड़ेराजपुर', 'कोण्डागांव', 'ढोढरा', '["ढोढरा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-5', 5, 'श्री आशीष डे', 'मु.का.अ. ज.पं. बड़ेराजपुर', '9244249975', 'बड़ेराजपुर', 'कोण्डागांव', 'रामपुर', '["रामपुर"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-6', 6, 'सुश्री अंजली नागेश', 'नायब तहसीलदार बड़ेराजपुर', '9399717736', 'बड़ेराजपुर', 'कोण्डागांव', 'बस्तरबुड्रा', '["बस्तरबुड्रा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-7', 7, 'श्री फणेश्वर सोम', 'नायब तहसीलदार बड़ेराजपुर/बांसकोट', '9770609423', 'बड़ेराजपुर', 'कोण्डागांव', 'पिटेचुवा', '["पिटेचुवा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-8', 8, 'श्री एस.एस. अरकरा', 'करारोपण अधिकारी, ज.पं. बड़ेराजपुर', '8827830345', 'बड़ेराजपुर', 'कोण्डागांव', 'खरगांव', '["खरगांव"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-9', 9, 'श्री मिनेश वर्मा', 'खाद्य निरीक्षक, बड़ेराजपुर', '9993797152', 'बड़ेराजपुर', 'कोण्डागांव', 'जिरीपारा', '["जिरीपारा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-10', 10, 'श्री सुनील कुमार निराला', 'उपअभियंता, केशकाल, पीएमजीएसवाय', '7987019590', 'बड़ेराजपुर', 'कोण्डागांव', 'बैजनपुरी', '["बैजनपुरी"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-11', 11, 'डॉ. अमीषा नेताम', 'पशु चिकित्सा सहायक शल्यज्ञ', '9644712578', 'बड़ेराजपुर', 'कोण्डागांव', 'खलारी', '["खलारी"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-12', 12, 'श्री सोनेसाय सोम', 'सहा.प.चि.क्षे.अधि.', '9881064908', 'बड़ेराजपुर', 'कोण्डागांव', 'कोसमी', '["कोसमी"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-13', 13, 'श्री विनोद नाग', 'ग्रामीण कृषि विस्तार अधिकारी', '9399580559', 'बड़ेराजपुर', 'कोण्डागांव', 'हात्मा', '["हात्मा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-14', 14, 'श्री देवेन्द्र नेताम', 'ग्रामीण कृषि विस्तार अधिकारी', '7987304134', 'बड़ेराजपुर', 'कोण्डागांव', 'कोरहोबेड़ा', '["कोरहोबेड़ा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-15', 15, 'श्री यशवंत कुमार सिंहा', 'सहा.प.चि.क्षे.अधि DMF', '8871956587', 'बड़ेराजपुर', 'कोण्डागांव', 'कोरगांव', '["कोरगांव"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-16', 16, 'श्री सेवक राम मरकाम', 'उद्यान विकास अधिकारी, बड़ेराजपुर', '7987191501', 'बड़ेराजपुर', 'कोण्डागांव', 'टेंवसा', '["टेंवसा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-17', 17, 'श्री के.के. मरकाम', 'वरिष्ठ कृषि विकास अधिकारी, बड़ेराजपुर', '9993221806', 'बड़ेराजपुर', 'कोण्डागांव', 'कलगांव', '["कलगांव"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-18', 18, 'श्रीमति वर्षा सलाम', 'WDT सदस्य आजीविका, कार्या.परि.क्रि.ए. वि.खं. - बड़ेराजपुर', '8889835885', 'बड़ेराजपुर', 'कोण्डागांव', 'कोंगेरा', '["कोंगेरा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-19', 19, 'श्री उत्तम कुमार चौधरी', 'अनुविभागीय अधिकारी (ग्रा.यां.से.)', '8770269963', 'बड़ेराजपुर', 'कोण्डागांव', 'सोनपुर', '["सोनपुर"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-20', 20, 'श्री विजय नाग', 'विकासखण्ड शिक्षा अधिकारी, बड़ेराजपुर', '9340244070', 'बड़ेराजपुर', 'कोण्डागांव', 'पेण्ड्रावन', '["पेण्ड्रावन"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-21', 21, 'श्री सौरभ चन्द्राकर', 'मण्डल संयोजक वि.खं.बड़ेराजपुर', '9907884884', 'बड़ेराजपुर', 'कोण्डागांव', 'होनावण्डी', '["होनावण्डी"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-22', 22, 'श्री रमेश मरकाम', 'अनु.वि.अ. जल संसाधन', '9424210616', 'बड़ेराजपुर', 'कोण्डागांव', 'बाड़ागांव', '["बाड़ागांव"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-23', 23, 'श्रीमती विमला भास्कर', 'परियोजना अधिकारी म.बा.वि.', '9406150451', 'बड़ेराजपुर', 'कोण्डागांव', 'काँदेकरा', '["काँदेकरा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-24', 24, 'श्री सुनील दास मानिकपुरी', 'वि.सम.एसबीएम, ज.पं. बड़ेराजपुर', '6266242549', 'बड़ेराजपुर', 'कोण्डागांव', 'मचली', '["मचली"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-25', 25, 'श्री गजेन्द्र कुमार ठाकुर', 'सहायक विकासखण्ड शिक्षा अधिकारी', '9098873745', 'बड़ेराजपुर', 'कोण्डागांव', 'पारोण्ड', '["पारोण्ड"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-26', 26, 'श्री सोनाराम यादव', 'खण्ड स्रोत समन्वयक', '8720091311', 'बड़ेराजपुर', 'कोण्डागांव', 'खजरावण्ड', '["खजरावण्ड"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-27', 27, 'सुश्री असमिता', 'मत्स्य निरीक्षक', '9685336041', 'बड़ेराजपुर', 'कोण्डागांव', 'आमगांव', '["आमगांव"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-28', 28, 'श्री अविनाश भाण्डेकर', 'ग्रामीण कृषि विस्तार अधिकारी', '7869787341', 'बड़ेराजपुर', 'कोण्डागांव', 'बड़ेराजपुर', '["बड़ेराजपुर"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-29', 29, 'श्री पी.एल. ठाकुर', 'पशु चिकित्सा अधिकारी, बड़ेराजपुर', '9009873653', 'बड़ेराजपुर', 'कोण्डागांव', 'छोटेराजपुर', '["छोटेराजपुर"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-30', 30, 'श्री लक्ष्मीकांत सोनबोईर', 'कार्यक्रम अधिकारी, वीबीजीरामजी', '7828299277', 'बड़ेराजपुर', 'कोण्डागांव', 'माड़ोकी खरगांव', '["माड़ोकी खरगांव"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-31', 31, 'श्री राम नेताम', 'सहा.प.चि.क्षे.अधि., पशु औषधालय', '9752044105', 'बड़ेराजपुर', 'कोण्डागांव', 'कोपरा', '["कोपरा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-32', 32, 'श्री सारस महादेवेकर', 'उपअभियंता, जल संसाधन विभाग', '9424289171', 'बड़ेराजपुर', 'कोण्डागांव', 'छिन्दली', '["छिन्दली"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-33', 33, 'श्री मुकुल देव कँवर', 'WDT सदस्य यांत्रिकी, कार्या.परि.क्रि. एजेंसी वि.खं. - बड़ेराजपुर', '7869244724', 'बड़ेराजपुर', 'कोण्डागांव', 'धामनपुरी', '["धामनपुरी"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-34', 34, 'श्री मनेश नेताम', 'ग्रामीण कृषि विस्तार अधिकारी', '7987909055', 'बड़ेराजपुर', 'कोण्डागांव', 'किबड़ा', '["किबड़ा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-35', 35, 'श्री सुरेश कुर्रे', 'श्रम निरीक्षक बड़ेराजपुर', '8839375359', 'बड़ेराजपुर', 'कोण्डागांव', 'बालेंगा', '["बालेंगा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-36', 36, 'श्री जगदीश नाग', 'ग्रामीण कृषि विस्तार अधिकारी', '7587145093', 'बड़ेराजपुर', 'कोण्डागांव', 'लिहागांव', '["लिहागांव"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-37', 37, 'श्रीमती सुधा यादव', 'ग्रामीण कृषि विस्तार अधिकारी', '7828301201', 'बड़ेराजपुर', 'कोण्डागांव', 'पलना', '["पलना"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-38', 38, 'श्री राजेश नेताम', 'सहा.प.चि.क्षे.अधि, पशु औषधालय', '9755994903', 'बड़ेराजपुर', 'कोण्डागांव', 'चिचाड़ी', '["चिचाड़ी"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-39', 39, 'श्री घनश्याम मरकाम', 'बीपीएम, एनआरएलएम बड़ेराजपुर', '7987592925', 'बड़ेराजपुर', 'कोण्डागांव', 'सालना', '["सालना"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-40', 40, 'श्री किशोर कुमार चन्द्राकर', 'उप अभियंता, आरईएस बड़ेराजपुर', '8821019937', 'बड़ेराजपुर', 'कोण्डागांव', 'मारंगपुरी', '["मारंगपुरी"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-41', 41, 'सुश्री निभा कोर्राम', 'उप अभियंता लो.स्वा.यां., बड़ेराजपुर', '6263129678', 'बड़ेराजपुर', 'कोण्डागांव', 'केरागांव', '["केरागांव"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-42', 42, 'श्री छगन कुमार', 'उपअभियंता, जल संसाधन विभाग', '8982456264', 'बड़ेराजपुर', 'कोण्डागांव', 'हरवेल', '["हरवेल"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-43', 43, 'श्री श्रवण कुमार नाग', 'ग्रामीण कृषि विस्तार अधिकारी', '7804898613', 'बड़ेराजपुर', 'कोण्डागांव', 'पीढ़ापाल', '["पीढ़ापाल"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-44', 44, 'श्री किशोर मरकाम', 'ग्रामीण कृषि विस्तार अधिकारी', '7974567198', 'बड़ेराजपुर', 'कोण्डागांव', 'नौकाबेड़ा', '["नौकाबेड़ा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-45', 45, 'श्री सुरेन्द्र प्रसाद मरकाम', 'सहा.प.चि.क्षे.अधि, पशु औषधालय', '9174844288', 'बड़ेराजपुर', 'कोण्डागांव', 'जोड़ेकेरा', '["जोड़ेकेरा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-46', 46, 'श्री डी डी नागवंशी', 'ग्रामीण कृषि विस्तार अधिकारी', '8458822595', 'बड़ेराजपुर', 'कोण्डागांव', 'गम्हरी', '["गम्हरी"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-47', 47, 'श्री कमल नारायण गिलहरे', 'बीपीएम रा.स्वा.मि., सीएचसी विश्रामपुरी', '9329253604', 'बड़ेराजपुर', 'कोण्डागांव', 'विश्रामपुरी ''अ''', '["विश्रामपुरी ''अ''"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-48', 48, 'डॉ. अनुराग भारती', 'खण्ड चिकित्सा अधिकारी, सीएचसी विश्रामपुरी', '8889255777', 'बड़ेराजपुर', 'कोण्डागांव', 'विश्रामपुरी ''ब''', '["विश्रामपुरी ''ब''"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-49', 49, 'श्रीमती रूपा मण्डावी', 'क्षेत्रीय समन्वयक, एनआरएलएम बड़ेराजपुर', '9617914777', 'बड़ेराजपुर', 'कोण्डागांव', 'बीरापारा', '["बीरापारा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-56', 1, 'श्री रवि कुमार सोरी', 'विकास विस्तार अधिकारी, केशकाल', '9425251101', 'केशकाल', 'कोण्डागांव', 'बटराली', '["बटराली"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-57', 2, 'श्री सुरेश मण्डावी', 'सहायक प्राध्यापक, केशकाल', '9425251102', 'केशकाल', 'कोण्डागांव', 'अरण्डी', '["अरण्डी"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-58', 3, 'सुश्री नीता नेताम', 'करारोपण अधिकारी, केशकाल', '9425251103', 'केशकाल', 'कोण्डागांव', 'तमोरा', '["तमोरा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-59', 4, 'श्री जितेन्द्र कुमार', 'उप अभियंता, केशकाल', '9425251104', 'केशकाल', 'कोण्डागांव', 'दादरगढ़', '["दादरगढ़"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-60', 5, 'श्री रमेश पोयाम', 'कृषि विकास अधिकारी, केशकाल', '9425251105', 'केशकाल', 'कोण्डागांव', 'सुरदोंग', '["सुरदोंग"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-61', 1, 'श्री दिनेश कुमार बघेल', 'विकास विस्तार अधिकारी, फरसगांव', '9425252101', 'फरसगांव', 'कोण्डागांव', 'पासंगी', '["पासंगी"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-62', 2, 'श्री शिवप्रसाद यादव', 'करारोपण अधिकारी, फरसगांव', '9425252102', 'फरसगांव', 'कोण्डागांव', 'बड़ाडोंगर', '["बड़ाडोंगर"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-63', 3, 'श्री योगेश मरकाम', 'उप अभियंता, फरसगांव', '9425252103', 'फरसगांव', 'कोण्डागांव', 'मांझीआठगांव', '["मांझीआठगांव"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-64', 4, 'श्रीमती संगीता पटेल', 'समन्वयक, फरसगांव', '9425252104', 'फरसगांव', 'कोण्डागांव', 'भोंगापाल', '["भोंगापाल"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-65', 5, 'श्री हरीश नाग', 'कृषि विस्तार अधिकारी, फरसगांव', '9425252105', 'फरसगांव', 'कोण्डागांव', 'पाटला', '["पाटला"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-66', 1, 'श्री महेन्द्र कुमार जैन', 'विकास विस्तार अधिकारी, कोंडागांव', '9425253101', 'कोंडागांव', 'कोण्डागांव', 'बनियागांव', '["बनियागांव"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-67', 2, 'श्री राजेश कुमार नेताम', 'उप अभियंता, कोंडागांव', '9425253102', 'कोंडागांव', 'कोण्डागांव', 'दहीकोंगा', '["दहीकोंगा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-68', 3, 'सुश्री गीतांजलि मण्डावी', 'करारोपण अधिकारी, कोंडागांव', '9425253103', 'कोंडागांव', 'कोण्डागांव', 'जुगानी', '["जुगानी"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-69', 4, 'श्री आशीष श्रीवास्तव', 'समन्वयक, कोंडागांव', '9425253104', 'कोंडागांव', 'कोण्डागांव', 'बम्हनी', '["बम्हनी"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-70', 5, 'श्रीमती किरण मरकाम', 'कृषि विकास अधिकारी, कोंडागांव', '9425253105', 'कोंडागांव', 'कोण्डागांव', 'लंजोड़ा', '["लंजोड़ा"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-71', 1, 'श्री मनोज कुमार नाग', 'विकास विस्तार अधिकारी, माकडी', '9425254101', 'माकडी', 'कोण्डागांव', 'अनंतपुर', '["अनंतपुर"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-72', 2, 'श्री कमल किशोर नेताम', 'उप अभियंता, माकडी', '9425254102', 'माकडी', 'कोण्डागांव', 'बालेंग', '["बालेंग"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-73', 3, 'सुश्री रीना कश्यप', 'करारोपण अधिकारी, माकडी', '9425254103', 'माकडी', 'कोण्डागांव', 'कांगोली', '["कांगोली"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-74', 4, 'श्री हेमंत कुमार साहू', 'कृषि विस्तार अधिकारी, माकडी', '9425254104', 'माकडी', 'कोण्डागांव', 'रांधना', '["रांधना"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
INSERT INTO public.nodal_officers (id, sno, name, designation, mobile, block, district, panchayat, panchayats, is_active) VALUES ('off-75', 5, 'श्रीमती देवकी कोर्राम', 'तकनीकी सहायक, माकडी', '9425254105', 'माकडी', 'कोण्डागांव', 'शामपुर', '["शामपुर"]'::jsonb, true) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, designation = EXCLUDED.designation, mobile = EXCLUDED.mobile, block = EXCLUDED.block, panchayat = EXCLUDED.panchayat, panchayats = EXCLUDED.panchayats;
